#!/bin/zsh

selection=$(fd -t d | fzf --multi --height=80% --border=rounded \
--preview='tree -C {}' --preview-window='45%,border-rounded' \
--prompt='Dirs > ' \
--bind='del:execute(rm -ri {+})' \
--bind='?:toggle-preview' \
--bind='alt-d:change-prompt(Dirs > )' \
--bind='alt-d:+reload(fd -t d)' \
--bind='alt-d:+change-preview(tree -C {})' \
--bind='alt-d:+refresh-preview' \
--bind='alt-f:change-prompt(Files > )' \
--bind='alt-f:+reload(fd -t f)' \
--bind='alt-f:+change-preview(bat {})' \
--bind='alt-f:+refresh-preview' \
--bind='ctrl-a:select-all' \
--bind='ctrl-x:deselect-all' \
--header '
ALT-D to display directories | ALT-F to display files
CTRL-A to select all | CTLR-x to deselect all
ENTER to edit | DEL to delete
? to toggle preview
'
)

if [ -z "$selection" ]; then
    return
fi

if [ -d "$selection" ]; then
    cd "$selection" || exit
else
    eval $EDITOR $(echo $selection | sed -e 's/\x00/ /g')
fi
