#!/bin/zsh

local -r dir=${1}

function _set_user_var() {
    value=$(echo -n ${2} | base64)
    printf "\033]1337;SetUserVar=%s=%s\007" ${1} $value
}

function _find_file() {
    if [ ! -z ${dir} ]; then
        fd -I -t f . "$dir" | awk '{print $1}'
    else
        fd -I -t f | awk '{print $1}'
    fi
}

function _find_dir() {
    if [ ! -z ${dir} ]; then
        fd -I -L -t d . "$dir" | awk '{print $1}'
    else
        fd -I -L -t d | awk '{print $1}'
    fi
}

export FIND_FILE=$(functions _find_file)
export FIND_DIR=$(functions _find_dir)

_set_user_var IS_EXPLORER "true"

selection=$(_find_dir | fzf --with-shell="zsh -c" --multi --height=80% --border=rounded \
--preview="tree -C {}" --preview-window="45%,border-rounded" \
--prompt="Dirs > " \
--bind="del:execute(rm -ri {+})" \
--bind="?:toggle-preview" \
--bind="ctrl-d:change-prompt(Dirs > )" \
--bind="ctrl-d:+reload(eval $FIND_DIR && _find_dir)" \
--bind="ctrl-d:+change-preview(tree -C {})" \
--bind="ctrl-d:+refresh-preview" \
--bind="ctrl-f:change-prompt(Files > )" \
--bind="ctrl-f:+reload(eval $FIND_FILE && _find_file)" \
--bind="ctrl-f:+change-preview(bat --color=always {})" \
--bind="ctrl-f:+refresh-preview" \
--bind="ctrl-a:select-all" \
--bind="ctrl-x:deselect-all" \
--header "
CTRL-D to display directories | CTRL-F to display files
CTRL-A to select all | CTRL-X to deselect all
ENTER to edit | DEL to delete
? to toggle preview
")

if [ -z "$selection" ]; then
    _set_user_var IS_EXPLORER "false"
    return
fi

if [ -d "$selection" ]; then
    cd "$selection" || exit
else
    eval "$EDITOR $selection"
fi

_set_user_var IS_EXPLORER "false"

unset -f _set_user_var
unset -f _find_file
unset -f _find_dir
