#!/bin/zsh

if [[ "$OSTYPE" == "msys" ]]; then
    if ! command -v nvim &> /dev/null; then
        scoop install main/neovim
        return
    else
        scoop update neovim
    fi
    return
fi

# If a previous installation of nvim exists, remove it.
if [ -f "$HOME/.local/bin/nvim" ]; then
    rm -R "$HOME/.local/bin/nvim"
fi

curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
mv nvim.appimage "$HOME/.local/bin/nvim"
