#!/bin/zsh

local -r dir=${1}

find_file() {
    if [ ! -z ${dir} ]; then
        fd -t f . "$dir" | awk '{print $1}'
    else
        fd -t f | awk '{print $1}'
    fi
}

local selection=$(find_file | fzf --multi --height=80% --border=rounded \
--preview="bat {}" --preview-window="45%,border-rounded" \
--prompt="Dirs > " \
--bind="del:execute(rm -ri {+})" \
--bind="?:toggle-preview" \
--bind="ctrl-a:select-all" \
--bind="ctrl-x:deselect-all" \
--header "
CTRL-a to select all | CTRL-x to deselect all
ENTER to edit | DEL to delete
CTRL-q to exit
? to toggle preview
"
)

if [ -z "$selection" ]; then
    return
fi

eval $EDITOR $(echo $selection | sed -e "s/\x00/ /g")
