#!/bin/sh

rm "$HOME/.zshrc"
rm "$HOME/.zprofile"
rm "$HOME/.zshenv"
rm "$HOME/.zsh_plugins.txt"
rm "$HOME/.zsh_plugins.zsh"
rm "$HOME/.p10k.zsh"
rm "$HOME/.zshfn"
rm "$HOME/.zshpy"
rm "$HOME/.gitconfig"
rm "$HOME/.gitignore"
rm "$HOME/.gittemplate.txt"
rm "$HOME/.config/nvim"
rm "$HOME/.clang-format"
rm "$HOME/.tmux.conf"
rm "$HOME/.config/bat"
rm "$HOME/.config/wezterm"
