# Export variables.
export EDITOR='nvim'
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# Check if we have antigen installed, if not, then install it.
ANTIGEN=~/antigen.zsh
if [[ ! -f $ANTIGEN ]]; then
	echo 'Downloading Antigen...'
	curl -L git.io/antigen > $ANTIGEN
fi

source ~/antigen.zsh

# Oh-my-zsh
antigen use oh-my-zsh

# oh-my-zsh libs
antigen bundle git
antigen bundle pip
antigen bundle command-not-found

# syntax highlighting
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search

# Load theme
antigen theme dracula/zsh dracula

# Finish up.
antigen apply

autoload -U compinit && compinit
autoload -U +X bashcompinit && bashcompinit

bindkey -v

# Vim aliases.
alias vi='nvim'
alias vim='nvim'
alias gvim='nvim'

# Grep aliases
alias grep='grep --color'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Emulates Apple's open.
alias open='xdg-open'

# Directory listings.
alias ls='ls -1 -hF --color=auto'
alias la='ls -A'

HISTFILE='$HOME/.zsh_history'
HISTSIZE=1024

setopt append_history
setopt share_history
setopt extended_history
setopt histignorealldups
setopt histignorespace
