# Export variables.
export EDITOR='nvim'
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export YSU_HARDCORE=1

# Load compinit for Windows (msys) and OSX since they don't enable it by default
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "darwin"* ]]; then
    autoload -Uz compinit
    compinit
fi

# Install antidote if necessary
ANTIDOTE=~/.antidote
if [ ! -d $ANTIDOTE ]; then
    echo "Downloading antidote"
    git clone --depth=1 https://github.com/mattmc3/antidote.git $ANTIDOTE
fi

source $ANTIDOTE/antidote.zsh

antidote load

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Vim aliases.
alias vi='nvim'
alias vim='nvim'

# On Windows only, override neovide so it opens with the size we want. Also it seems the
# latest version of Neovide has an issue with forking correctly on git bash, so ensure it
# doesn't block the terminal when started.
if [[ "$OSTYPE" == "msys" ]]; then
    alias neovide='(neovide --grid 100x50 &)'
fi

# Grep aliases
alias grep='grep --color'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Emulates Apple's open. Only applies to Linux (linux-gnu) and Windows (msys).
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    alias open='xdg-open'
elif [[ "$OSTYPE" == "msys" ]]; then
    alias open='start'
fi

# Allow Windows to open bash without any settings. This is mainly to address an issue
# where certain paths don't work in zsh.
if [[ "$OSTYPE" == "msys" ]]; then
    alias bash='bash --norc --noprofile'
fi

# Directory listings.
alias ls='ls -1 -hF --color=auto'
alias la='ls -A'

bindkey '^[[Z' autosuggest-accept

export LS_COLORS="$LS_COLORS:ow=1;34:tw=1;34:"

fpath+=(~/.zshfn)
autoload -Uz tar_zstd
autoload -Uz untar_zstd
autoload -Uz nvim_update

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

if [[ "$OSTYPE" == "msys" ]]; then
    keep_current_path() {
        printf "\e]9;9;%s\e\\" "$(cygpath -w "$PWD")"
    }
    precmd_functions+=(keep_current_path)
fi
